# Generated by Django 3.1.7 on 2021-03-23 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Present_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Permanant_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_Of_Birth', models.DateField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='User')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
