# Generated by Django 3.1.7 on 2021-03-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_userprofilem_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilem',
            name='Date_Of_Birth',
        ),
    ]
