# Generated by Django 3.1.7 on 2021-03-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_remove_userprofilem_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilem',
            name='Country_name',
        ),
    ]
