# Generated by Django 3.1.7 on 2021-03-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_itementrym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itementrym',
            old_name='unit',
            new_name='Unit',
        ),
    ]
