# Generated by Django 3.1.7 on 2021-03-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20210324_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itementrym',
            name='Unit',
        ),
    ]
