# Generated by Django 3.1.7 on 2021-03-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_remove_itementrym_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementrym',
            name='Unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
