# Generated by Django 3.1.7 on 2021-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_itementrym_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInfoM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Suppliername', models.CharField(blank=True, max_length=255, null=True)),
                ('Address', models.TextField(blank=True, max_length=2000, null=True)),
                ('Phone', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
