# Generated by Django 3.1.7 on 2021-03-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_supplierinfom'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesInformationM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Depertment', models.CharField(blank=True, max_length=255, null=True)),
                ('Employees_id', models.CharField(blank=True, max_length=255, null=True)),
                ('Present_address', models.TextField(blank=True, max_length=1500, null=True)),
                ('Permanent_address', models.TextField(blank=True, max_length=1500, null=True)),
                ('Date_of_Birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
