# Generated by Django 3.1.7 on 2021-03-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_purchageinfo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='purchageinfo',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='purchageinfo',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='purchageinfo',
            name='Grant_total',
        ),
        migrations.RemoveField(
            model_name='purchageinfo',
            name='Sub_Total',
        ),
        migrations.RemoveField(
            model_name='purchageinfo',
            name='Total',
        ),
    ]
