# Generated by Django 3.1.7 on 2021-03-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_auto_20210327_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchageinfo',
            name='Rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
