# Generated by Django 3.1.7 on 2021-03-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0016_auto_20210327_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchageExtendM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pdate', models.DateField(blank=True, null=True)),
                ('Invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Vat', models.IntegerField(blank=True, null=True)),
                ('Less', models.IntegerField(blank=True, null=True)),
                ('Supplier_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.supplierinfom')),
            ],
        ),
        migrations.CreateModel(
            name='PurchageInfoM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Rate', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PurchageInfo',
        ),
    ]
