# Generated by Django 3.1.7 on 2021-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0018_purchageinfom_purchageex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchageinfom',
            name='purchageEx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
