# Generated by Django 3.1.7 on 2021-03-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0020_remove_purchageinfom_purchageex'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchageinfom',
            name='pex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.purchageextendm'),
        ),
    ]
