# Generated by Django 3.1.7 on 2021-03-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0021_purchageinfom_pex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchageinfom',
            name='pex',
        ),
        migrations.AddField(
            model_name='purchageinfom',
            name='Invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchageinfom',
            name='Less',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchageinfom',
            name='Pdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchageinfom',
            name='Supplier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.supplierinfom'),
        ),
        migrations.AddField(
            model_name='purchageinfom',
            name='Vat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
