# Generated by Django 3.1.7 on 2021-05-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0023_auto_20210327_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchageextendm',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
