# Generated by Django 3.1.7 on 2021-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0025_auto_20210519_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchageinfom',
            name='Invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
