# Generated by Django 3.1.7 on 2021-05-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0027_auto_20210519_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='issueInfoM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Rate', models.CharField(blank=True, max_length=255, null=True)),
                ('Invoice_nos', models.CharField(blank=True, max_length=100, null=True)),
                ('pex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.purchageextendm')),
            ],
        ),
        migrations.CreateModel(
            name='IssueExtendM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pdate', models.DateField(blank=True, null=True)),
                ('Invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.employeesinformationm')),
            ],
        ),
    ]
